
{ port-in-virtual:$$AWAS$fptc_base$A2B#in[ error:$$AWAS$example/fptc/fptc_base.awas$Fault#late ]
port-in-virtual:$$AWAS$fptc_base$B2A#in[ error:$$AWAS$example/fptc/fptc_base.awas$Fault#late ]
port-in:$$AWAS$fptc_base$A#aIn[ error:$$AWAS$example/fptc/fptc_base.awas$Fault#late ]
port-in:$$AWAS$fptc_base$B#bIn[ error:$$AWAS$example/fptc/fptc_base.awas$Fault#late ]
port-out-virtual:$$AWAS$fptc_base$A2B#out[ error:$$AWAS$example/fptc/fptc_base.awas$Fault#late ]
port-out-virtual:$$AWAS$fptc_base$B2A#out[ error:$$AWAS$example/fptc/fptc_base.awas$Fault#late ]
port-out:$$AWAS$fptc_base$A#aOut[ error:$$AWAS$example/fptc/fptc_base.awas$Fault#late ]
port-out:$$AWAS$fptc_base$B#bOut[ error:$$AWAS$example/fptc/fptc_base.awas$Fault#late ] } 

 States : 

 Behaviors: 
behavior:$$AWAS$fptc_base$B#b5
behavior:$$AWAS$fptc_base$A#b1